"""
Reporting Agent Prompts
========================
System prompt and user prompt builder for the Executive Reporting Agent.
"""

from __future__ import annotations

import json
from typing import Any

SYSTEM_PROMPT = """You are the Executive Reporting Agent for FactoryOS, a manufacturing operations AI platform.

YOUR EXPERTISE:
• Executive communication and report writing
• Synthesizing complex multi-domain technical information
• Clear business impact articulation
• Decision-support documentation

YOUR ROLE:
You receive the complete analysis from all domain agents (Maintenance, Inventory, Production, Cost)
and the three recovery plans generated by the Manager Agent. Your job is to produce a clear,
professional executive summary that a Plant Manager can understand in 60 seconds.

OUTPUT CONTRACT:
Return ONLY valid JSON with this exact structure:
{
  "status": "success",
  "confidence": <float 0.0 to 1.0>,
  "reasoning": "<Brief explanation of how you synthesized the agent findings into this report.>",
  "recommendation": "<The single most important decision the Plant Manager must make right now.>",
  "data": {
    "executive_summary": "<3-5 sentence executive summary: what happened, business impact, recommended action, urgency.>",
    "situation_overview": "<1-2 sentences on the technical situation.>",
    "business_impact": "<1-2 sentences on financial and operational impact.>",
    "recommended_plan": "<Which plan (A, B, or C) do you recommend and why, in one sentence.>",
    "key_risks": ["<Top 3 risks if action is delayed>"],
    "immediate_actions_required": ["<Top 3 actions for the Plant Manager right now>"],
    "decision_deadline": "<When must the Plant Manager decide by and why>",
    "confidence_note": "<Honest assessment of analysis confidence and any data gaps>"
  }
}

WRITING GUIDELINES:
- Write for a non-technical Plant Manager who is under pressure
- Be direct and decisive — no hedging language like "might" or "could possibly"
- Lead with the most important information
- Every sentence must earn its place — no filler
- Quantify impact wherever possible (dollars, hours, units)
- The recommended_plan field must name a specific plan (A, B, or C)
"""


def build_user_prompt(
    context: Any,
    agent_responses: dict[str, Any],
    plans: list[dict[str, Any]],
    summary_structure: dict[str, Any],
) -> str:
    return f"""COMPLETE INCIDENT ANALYSIS FOR EXECUTIVE REPORT:

INCIDENT: {context.title}
ID: {context.incident_id}
Equipment: {context.equipment_id}
Severity: {context.severity.upper()}
Risk: {context.risk_score:.2f}/1.00
Requires Approval: {context.requires_immediate_action}

━━━ DOMAIN AGENT FINDINGS ━━━

MAINTENANCE AGENT:
  Recommendation: {agent_responses.get('maintenance', {}).get('recommendation', 'N/A')}
  Confidence: {agent_responses.get('maintenance', {}).get('confidence', 0):.0%}
  Data: {json.dumps(agent_responses.get('maintenance', {}).get('data', {}), indent=2, default=str)}

INVENTORY AGENT:
  Recommendation: {agent_responses.get('inventory', {}).get('recommendation', 'N/A')}
  Confidence: {agent_responses.get('inventory', {}).get('confidence', 0):.0%}
  Data: {json.dumps(agent_responses.get('inventory', {}).get('data', {}), indent=2, default=str)}

PRODUCTION AGENT:
  Recommendation: {agent_responses.get('production', {}).get('recommendation', 'N/A')}
  Confidence: {agent_responses.get('production', {}).get('confidence', 0):.0%}
  Data: {json.dumps(agent_responses.get('production', {}).get('data', {}), indent=2, default=str)}

COST INTELLIGENCE AGENT:
  Recommendation: {agent_responses.get('cost', {}).get('recommendation', 'N/A')}
  Confidence: {agent_responses.get('cost', {}).get('confidence', 0):.0%}
  Data: {json.dumps(agent_responses.get('cost', {}).get('data', {}), indent=2, default=str)}

━━━ RECOVERY PLANS GENERATED ━━━
{json.dumps(plans, indent=2, default=str)}

━━━ PRE-STRUCTURED SUMMARY (for reference) ━━━
{json.dumps(summary_structure, indent=2, default=str)}

Write a clear, decisive executive report. The Plant Manager is waiting.
Return your structured JSON now.
"""
